# Form implementation generated from reading ui file 'denklem-ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.baslikLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.baslikLabel.setGeometry(QtCore.QRect(250, 0, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.baslikLabel.setFont(font)
        self.baslikLabel.setObjectName("baslikLabel")
        self.denklemBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.denklemBox.setGeometry(QtCore.QRect(10, 50, 381, 41))
        self.denklemBox.setObjectName("denklemBox")
        self.denklemBox.addItem("")
        self.denklemBox.addItem("")
        self.denklemBox.addItem("")
        self.denklemBox.addItem("")  # Yeni denklem sistemleri seçeneği
        self.metodBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.metodBox.setGeometry(QtCore.QRect(410, 50, 381, 41))
        self.metodBox.setObjectName("metodBox")
        self.metodBox.addItem("")
        self.metodBox.addItem("")
        self.metodBox.addItem("")
        self.metodBox.addItem("")  # Yeni Gauss Eliminasyon seçeneği
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 150, 781, 331))
        self.listWidget.setObjectName("listWidget")
        self.sonucLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.sonucLabel.setGeometry(QtCore.QRect(260, 500, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.sonucLabel.setFont(font)
        self.sonucLabel.setObjectName("sonucLabel")
        self.sonucButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sonucButton.setGeometry(QtCore.QRect(340, 100, 121, 41))
        self.sonucButton.setObjectName("sonucButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baslikLabel.setText(_translate("MainWindow", "Denklem Cozucu"))
        self.denklemBox.setItemText(0, _translate("MainWindow", "x^2 - 4"))
        self.denklemBox.setItemText(1, _translate("MainWindow", "sin(x) - x/2"))
        self.denklemBox.setItemText(2, _translate("MainWindow", "e^(-x) - x"))
        self.denklemBox.setItemText(3, _translate("MainWindow", "Lineer Denklem Sistemi"))
        self.metodBox.setItemText(0, _translate("MainWindow", "Newton-Raphson Yontemi"))
        self.metodBox.setItemText(1, _translate("MainWindow", "Bisection Yontemi"))
        self.metodBox.setItemText(2, _translate("MainWindow", "Sekant Yontemi"))
        self.metodBox.setItemText(3, _translate("MainWindow", "Gauss Eliminasyon Yontemi"))
        self.sonucLabel.setText(_translate("MainWindow", "Sonuc:"))
        self.sonucButton.setText(_translate("MainWindow", "Hesapla"))
